### ISSUE TITLE
Help command

### ISSUE THREAD

**Issue by promise** [promise/ytdl-discord-bot#3]
Making a help command explaining each command in depth and also making it easy for new commands to be added could be cool.

- Preferably having the description of the command inside the command file, and so the help command gets that description from all the files. And displays it in a neat embed.
- Also make it searchable, if possible.

**Comment by Purhan** [comment]
hi @promise, I'd like to work on this issue. Are there any particular contribution guidelines that I have to follow?

**Comment by promise** [comment]
As long as it works and doesn't look like spaghetti code then I don't see any reason to not accept it. This repository is meant to help coders make their own music bot, so please keep it nice and clean. Also, feel free to add some comments.
@Purhan I hope this clarifies. Thanks for contributing!

**Comment by Purhan** [comment]
@promise Please take a look at PR #28, I have attached a screenshot of the command. You may want to look at the description of each command since I may not have made the best decisions while choosing them.
